#!/usr/bin/env bash
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd "${script_dir}/.." && pwd)"
build_dir="${script_dir}/.pio/build/esp32dev"
source_firmware="${build_dir}/firmware.bin"
target_fw_dir="${repo_root}/backend/firmware_template/files"
catalog_path="${repo_root}/backend/firmware_template/catalog.json"

run_build() {
  if command -v pio >/dev/null 2>&1; then
    (cd "${script_dir}" && pio run -e esp32dev)
    return
  fi
  (cd "${script_dir}" && python3 -m platformio run -e esp32dev)
}

compute_sha256() {
  local file_path="$1"
  if command -v shasum >/dev/null 2>&1; then
    shasum -a 256 "${file_path}" | awk '{print $1}'
    return
  fi
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum "${file_path}" | awk '{print $1}'
    return
  fi

  python3 - "${file_path}" <<'PY'
import hashlib
import pathlib
import sys

path = pathlib.Path(sys.argv[1])
digest = hashlib.sha256(path.read_bytes()).hexdigest()
print(digest)
PY
}

upsert_catalog_entry() {
  local version="$1"
  local filename="$2"
  local checksum="$3"
  local catalog_file="$4"

  python3 - "${catalog_file}" "${version}" "${filename}" "${checksum}" <<'PY'
import json
import os
import time
import sys

catalog_file = sys.argv[1]
version = sys.argv[2]
filename = sys.argv[3]
checksum = sys.argv[4]

payload = {
    "schema_version": 1,
    "updated_at": 0,
    "firmwares": [],
}

if os.path.isfile(catalog_file):
    try:
        with open(catalog_file, "r", encoding="utf-8") as f:
            loaded = json.load(f)
        if isinstance(loaded, dict):
            payload = loaded
    except Exception:
        pass

if not isinstance(payload.get("firmwares"), list):
    payload["firmwares"] = []

entry = {
    "agent_type": "esp32",
    "version": version,
    "installable": True,
    "ota_file": filename,
    "ota_sha256": checksum,
    "factory_file": filename,
    "factory_sha256": checksum,
    "notes": "generated by esp-agent/create-fw.sh",
}

updated = False
for idx, item in enumerate(payload["firmwares"]):
    if not isinstance(item, dict):
        continue
    agent_type = str(item.get("agent_type") or "").strip().lower() or "esp32"
    item_version = str(item.get("version") or "").strip()
    if agent_type == "esp32" and item_version == version:
        merged = dict(item)
        merged.update(entry)
        payload["firmwares"][idx] = merged
        updated = True
        break

if not updated:
    payload["firmwares"].append(entry)

def version_key(item):
    raw = str(item.get("version") or "0.0.0")
    parts = raw.split(".")
    if len(parts) != 3:
        return (0, 0, 0)
    try:
        return (int(parts[0]), int(parts[1]), int(parts[2]))
    except Exception:
        return (0, 0, 0)

payload["firmwares"] = sorted(payload["firmwares"], key=version_key, reverse=True)
payload["schema_version"] = int(payload.get("schema_version") or 1)
payload["updated_at"] = time.time()

os.makedirs(os.path.dirname(catalog_file), exist_ok=True)
with open(catalog_file, "w", encoding="utf-8") as f:
    json.dump(payload, f, indent=2)
    f.write("\n")
PY
}

run_build

if [ ! -f "${source_firmware}" ]; then
  echo "Build completed but firmware file was not found: ${source_firmware}" >&2
  exit 1
fi

echo "Build succeeded: ${source_firmware}"
read -r -p "Copy firmware to ${target_fw_dir}? [y/N]: " copy_choice

case "${copy_choice}" in
  y|Y|yes|YES)
    read -r -p "Enter firmware version (x.y.z): " version
    if [[ ! "${version}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
      echo "Invalid version format. Expected x.y.z." >&2
      exit 1
    fi

    mkdir -p "${target_fw_dir}"
    target_filename="esp32-ir-client-v${version}.bin"
    target_path="${target_fw_dir}/${target_filename}"
    cp -f "${source_firmware}" "${target_path}"

    checksum="$(compute_sha256 "${target_path}")"
    upsert_catalog_entry "${version}" "${target_filename}" "${checksum}" "${catalog_path}"

    echo "Copied firmware to: ${target_path}"
    echo "SHA-256: ${checksum}"
    echo "Catalog entry updated: ${catalog_path}"
    echo "Fields set: ota_file=${target_filename}, factory_file=${target_filename}"
    ;;
  *)
    echo "Build finished. No file was copied."
    ;;
esac
